name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Publish
        run: >
          cargo workspaces publish
          --yes
          --locked
          --from-git
          --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
