name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - '.github/scripts/**'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - '.github/scripts/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-backends:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend:
          - crossterm
          - termion

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --no-default-features --features "derive ${{ matrix.backend }}" --verbose

  test-wasm-backend:
    # TODO: This takes too long to run. Might enable it again later.
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Run wasm tests
        run: wasm-pack test --headless --chrome --features wasm --no-default-features

  test-workspace:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --workspace --verbose
